import { jsPDF } from "jspdf";

/**
 * Exports election results to a CSV file.
 * @param {string} filename 
 * @param {Array} results - Array of { name, votes }
 * @param {string} adminAddress 
 * @param {string} signature - Cryptographic signature of the results
 */
export const exportToCSV = (filename, results, adminAddress, signature) => {
  let csvContent = "data:text/csv;charset=utf-8,";
  csvContent += "Candidate Name,Votes\n";
  
  results.forEach(row => {
    csvContent += `${row.name},${row.votes}\n`;
  });
  
  csvContent += `\nVerification Metadata\n`;
  csvContent += `Admin Address,${adminAddress}\n`;
  csvContent += `Signature,${signature}\n`;
  
  const encodedUri = encodeURI(csvContent);
  const link = document.createElement("a");
  link.setAttribute("href", encodedUri);
  link.setAttribute("download", `${filename}.csv`);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
};

/**
 * Exports election results to a PDF file.
 * @param {string} filename 
 * @param {string} title 
 * @param {Array} results 
 * @param {string} adminAddress 
 * @param {string} signature 
 */
export const exportToPDF = (filename, title, results, adminAddress, signature) => {
  const doc = new jsPDF();
  
  // Header
  doc.setFontSize(22);
  doc.setTextColor(99, 102, 241); // Indigo-500
  doc.text("SecureVote Official Report", 105, 20, { align: "center" });
  
  doc.setFontSize(16);
  doc.setTextColor(30, 41, 59); // Slate-800
  doc.text(title, 105, 35, { align: "center" });
  
  doc.setDrawColor(226, 232, 240); // Slate-200
  doc.line(20, 45, 190, 45);
  
  // Table Header
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text("Candidate Name", 30, 60);
  doc.text("Total Votes", 150, 60, { align: "right" });
  
  doc.line(20, 65, 190, 65);
  
  // Table Rows
  doc.setFont("helvetica", "normal");
  let yPos = 75;
  results.forEach((row, idx) => {
    if (yPos > 250) {
      doc.addPage();
      yPos = 20;
    }
    doc.text(row.name, 30, yPos);
    doc.text(row.votes.toString(), 150, yPos, { align: "right" });
    yPos += 10;
  });
  
  doc.line(20, yPos, 190, yPos);
  
  // Signature Section
  yPos += 20;
  if (yPos > 240) {
    doc.addPage();
    yPos = 20;
  }
  
  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.text("Cryptographic Verification", 20, yPos);
  yPos += 10;
  
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.text(`Admin Payer/Signer: ${adminAddress}`, 20, yPos);
  yPos += 5;
  
  doc.setFontSize(7);
  doc.text("Signature:", 20, yPos);
  yPos += 5;
  const splitSignature = doc.splitTextToSize(signature, 170);
  doc.text(splitSignature, 20, yPos);
  
  // Footer
  const totalPages = doc.internal.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(148, 163, 184); // Slate-400
    doc.text(`Page ${i} of ${totalPages} - Generated by SecureVote dApp`, 105, 285, { align: "center" });
  }
  
  doc.save(`${filename}.pdf`);
};
